### ISSUE TITLE
Carbon flux: use latitude, longitude and day of year in predictions?

### ISSUE THREAD

**Issue by stsievert** [pyviz-topics/EarthML#10]
I'd like a better explanation of the motivation, and some domain knowledge to know what variables to exclude.

**Comment by stsievert** [comment]
I see latitude + day of year as being most important because those variables determine how much sunlight is received.

Here are some experiments on the clustering algorithm when using latitude, longitude and day of year (DOY) (as well as the measured variable, carbon flux). 

|             | Without lat/lon | With lat/lon |
|:-----------:|:---------------:|:------------:|
| **Without DOY** | <img width="508" alt="nodoy-nolatlon" src="https://user-images.githubusercontent.com/1320475/44215680-a7ddd480-a162-11e8-86e0-2ef105414df3.png"> | <img width="516" alt="nodoy-latlon" src="https://user-images.githubusercontent.com/1320475/44215688-ad3b1f00-a162-11e8-9f96-882f1ae1991b.png"> |
| **With DOY**    | <img width="521" alt="doy-nolatlon" src="https://user-images.githubusercontent.com/1320475/44215713-b926e100-a162-11e8-8ed2-06eec7edd271.png"> | <img width="513" alt="doy-latlon" src="https://user-images.githubusercontent.com/1320475/44215721-c0e68580-a162-11e8-85d5-33a16ac2e6a3.png">|

More detail on the clustering is present with more data received, naturally. I think this well help with prediction performance. I think longitude should be left out; I can see it as being confounding, though the clustering picks up on it.

**Comment by jbednar** [comment]
It's hard to see how the longitude will help anything, so I'd vote for not including it.

**Comment by ebo** [comment]
In many places there are clear env gradients either in lat or lon.  In 
this specific case I am not sure if it would make a difference or if you 
are working on a general tool.

**Comment by jbednar** [comment]
Right; over a relatively small region of the globe, lon would be a a perfectly reasonable feature to include.  But for a global model, it just seems more confusing than helpful, likely to lead to overfitting and poor generalization, unless recoded as something like "distance from the nearest coastline" or something else more meaningful at a global scale.

**Comment by jbednar** [comment]
Any and all advice welcome!!!
