### ISSUE TITLE
publishing example in peer reviewed journal

### ISSUE THREAD

**Issue by ebo** [pyviz-topics/EarthML#83]
While driving with my wife for the holidays we got to talking about some apps her and her field crews recently published in Applications in Plant Sciences.  It got me to thinking of an example I started playing with one night which scrapes local forecast information for her field sites, so that they can receive site specific forecasts targeting when they expect to be at the field sites.  Since they are often gone for a month or two at a time, these have to be regenerated on the fly...

Anyway, I reached out to the editor regarding copyright and got the following reply:

"...Regarding the copyright/license, articles published in APPS are published under a Creative Commons license. With Creative Commons licenses, the author retains copyright and the public is allowed to reuse the content. The author grants the Botanical Society of America a license to publish the article. ..."

is CC an acceptable copyright for one of the notebooks?  I figure that I could work this up as an example for either EarthML or EarthSIM, and it could also be published with APPS.  

I thought I would ask before spending much time on it as I can easily get it to the point where it is useful for my wife and her field crew, but it is an interesting offshoot to things I already discussed with weather/climate data collection.

**Comment by jbednar** [comment]
Would be great to have as a contribution, but closing for now as it's not actively being worked on that I know of. In any case the licensing sounds fine to me!  As of now, new examples go into https://github.com/pyviz-topics/examples, and each one can have its own license as needed, as long as it's an open-source license.
