### ISSUE TITLE
Bug at end of resampling docs in tutorial

### ISSUE THREAD

**Issue by nickhand** [pyviz-topics/EarthML#96]
At the end of [this page](http://earthml.pyviz.org/tutorial/03_Alignment_and_Preprocessing.html) of the docs, the resampling section has a couple of bugs. 

I think it should read:

```python
res_1000 = 1000
x_1000 = np.arange(xmin, xmax, res_1000)
y_1000 = np.arange(ymin, ymax, res_1000)

diff_res_1000 = (
    diff_regridded.groupby_bins("x", x_1000, labels=x_1000[:-1])
    .mean(dim="x")
    .groupby_bins("y", y_1000, labels=y_1000[:-1])
    .mean(dim="y")
    .rename(x_bins="x", y_bins="y")
)
diff_res_1000
```

**Comment by nickhand** [comment]
Happy to put a PR in (and thanks for the great docs and examples!)

**Comment by jbednar** [comment]
Ooh, I think you're right.  A PR will be gratefully accepted.
